### ISSUE TITLE
GLSP upgrade to 2.2.1 issue with EMSModelServerAccess

### ISSUE THREAD

**Issue by amiths89** [eclipse-emfcloud/modelserver-glsp-integration#59]
I am trying to run this project but it looks there is an issue, i was seeing the same issue as https://github.com/eclipse-emfcloud/modelserver-glsp-integration/issues/58 here so i decided to upgrade it to 2.2.1 for which i updated the client side code for this. And i was able to start the application but i get the below error in the tasklist-diagram which could be due to not configuring the server side with the 2.2.1 update which am not really sure. Is there a solution for this or atleast an updated version of this project with glsp 2.2.1

_Error during model loading
org.eclipse.glsp.server.types.GLSPServerException: Error during model loading
	at org.eclipse.emfcloud.modelserver.glsp.EMSModelServerAccess.getSemanticModel(EMSModelServerAccess.java:82)
	at org.eclipse.emfcloud.modelserver.glsp.notation.integration.EMSNotationSourceModelStorage.doLoadSourceModel(EMSNotationSourceModelStorage.java:29)
	at org.eclipse.emfcloud.modelserver.glsp.EMSSourceModelStorage.loadSourceModel(EMSSourceModelStorage.java:33)
	at org.eclipse.glsp.server.features.core.model.RequestModelActionHandler.executeAction(RequestModelActionHandler.java:75)
	at org.eclipse.emfcloud.modelserver.glsp.actions.handlers.EMSRequestModelActionHandler.executeAction(EMSRequestModelActionHandler.java:31)
	at org.eclipse.emfcloud.modelserver.glsp.actions.handlers.EMSRequestModelActionHandler.executeAction(EMSRequestModelActionHandler.java:22)
	at org.eclipse.glsp.server.actions.AbstractActionHandler.execute(AbstractActionHandler.java:53)
	at org.eclipse.glsp.server.internal.actions.DefaultActionDispatcher.runAction(DefaultActionDispatcher.java:198)
	at org.eclipse.glsp.server.internal.actions.DefaultActionDispatcher.handleAction(DefaultActionDispatcher.java:176)
	at org.eclipse.glsp.server.internal.actions.DefaultActionDispatcher.handleNextAction(DefaultActionDispatcher.java:163)
	at org.eclipse.glsp.server.internal.actions.DefaultActionDispatcher.runThread(DefaultActionDispatcher.java:149)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not parse 'data' field
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.eclipse.emfcloud.modelserver.glsp.EMSModelServerAccess.getSemanticModel(EMSModelServerAccess.java:79)
	... 11 more
Caused by: java.lang.RuntimeException: Could not parse 'data' field
	at org.eclipse.emfcloud.modelserver.internal.client.ModelServerClientDelegate.lambda$require$25(ModelServerClientDelegate.java:856)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.eclipse.emfcloud.modelserver.internal.client.ModelServerClientDelegate.require(ModelServerClientDelegate.java:856)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at org.eclipse.emfcloud.modelserver.client.Response.body(Response.java:41)
	at org.eclipse.emfcloud.modelserver.internal.client.ModelServerClientDelegate.lambda$cacheModelType$3(ModelServerClientDelegate.java:205)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.eclipse.emfcloud.modelserver.internal.client.ModelServerClientDelegate$3.onResponse(ModelServerClientDelegate.java:818)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more_

**Comment by Orangewithsugar** [comment]
Hi , so how you resolve this issue then?

**Comment by amiths89** [comment]
I had accidently created this. The correct one in this following post. Follow the link and in the comments it will direct you to another post which has the solution. https://github.com/eclipse-emfcloud/emfcloud/discussions/234

**Comment by Orangewithsugar** [comment]
Many thanks~
